SELECT * FROM AspNetRoles
SELECT * FROM AspNetRoleClaims
SELECT * FROM AspNetUsers
SELECT * FROM AspNetUserClaims
SELECT * FROM AspNetUserLogins
SELECT * FROM AspNetUserRoles
SELECT * FROM AspNetUserTokens
SELECT * FROM PersistedGrants
SELECT * FROM DeviceCodes
SELECT * FROM __EFMigrationsHistory